apiVersion: v1
kind: Service
metadata:
  name: basic-app-service
spec:
  selector:
    #################### matchLabels:  //This is assumed as it's old method
    pod-label-name: basic-app
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080
  type: LoadBalancer
